// Mico Work Match — job data (factory/manufacturing)
// Photo: hero image for each job (real photography)
window.WM_JOBS = [
  {
    id: "J-20451",
    title: "自動車部品の組立・検査",
    company: "青葉精機 株式会社",
    companySize: "従業員 820名",
    location: "愛知県 豊田市",
    locationShort: "豊田市",
    access: "名鉄三河線「豊田市」駅よりバス15分",
    wage: 1680,
    wageType: "時給",
    wageNote: "月収例 33.6万円＋残業手当",
    category: "製造",
    subcategory: "組立・検査",
    shift: "2交替 / 昼勤あり",
    tags: ["寮費無料", "未経験OK", "週払いOK", "カップル入寮"],
    photo: "assets/job-factory.jpeg",
    color: "#2a2eea",
    color2: "#5e60ff",
    accent: "#dcf142",
    artLabel: "FACTORY · ASSEMBLY",
    artIcon: "precision_manufacturing",
    match: 94,
    matchReason: "希望の寮・時給条件に近いです",
    highlights: [
      "入社祝い金 最大30万円",
      "社員食堂（1食300円〜）",
      "個室寮・家電家具付き",
    ],
    desc: "大手自動車メーカー向けの自動車部品を製造する工場での組立・検査のお仕事です。ライン作業が中心で、マニュアルが整備されているため未経験の方でも安心して始められます。",
    shiftDetails: ["早番: 6:30〜15:15", "遅番: 15:15〜24:00"],
    welfare: ["社会保険完備", "有給休暇", "交通費支給", "作業着貸与", "寮費0円 (12ヶ月まで)"],
  },
  {
    id: "J-20452",
    title: "食品工場での包装・仕分け",
    company: "ハルマチフーズ",
    companySize: "従業員 350名",
    location: "埼玉県 草加市",
    locationShort: "草加市",
    access: "東武スカイツリーライン「谷塚」駅徒歩8分",
    wage: 1320,
    wageType: "時給",
    wageNote: "月収例 24.5万円",
    category: "製造",
    subcategory: "食品・包装",
    shift: "日勤のみ",
    tags: ["日勤のみ", "冷暖房完備", "女性活躍中", "駅チカ"],
    photo: "assets/job-retail.jpeg",
    color: "#2a2eea",
    color2: "#5e60ff",
    accent: "#dcf142",
    artLabel: "FOOD PACKING",
    artIcon: "restaurant",
    match: 88,
    matchReason: "日勤×駅チカの希望に合致",
    highlights: [
      "土日休み固定",
      "制服無料貸与",
      "研修期間も同時給",
    ],
    desc: "冷凍惣菜の包装・ラベル貼り・仕分けのお仕事です。ほとんどが座り作業で、体への負担が少ない環境です。",
    shiftDetails: ["日勤: 8:30〜17:30 (実働8h)"],
    welfare: ["社保完備", "有給休暇", "社員割引あり", "制服貸与"],
  },
  {
    id: "J-20453",
    title: "半導体装置のオペレーター",
    company: "エヌケイ電子",
    companySize: "従業員 1200名",
    location: "三重県 四日市市",
    locationShort: "四日市市",
    access: "JR関西本線「南四日市」駅より送迎バス",
    wage: 1850,
    wageType: "時給",
    wageNote: "月収例 38.2万円＋皆勤手当",
    category: "製造",
    subcategory: "半導体",
    shift: "3交替",
    tags: ["高時給", "寮費無料", "正社員登用", "送迎あり"],
    photo: "assets/job-factory.jpeg",
    color: "#2a2eea",
    color2: "#5e60ff",
    accent: "#dcf142",
    artLabel: "SEMICONDUCTOR",
    artIcon: "memory",
    match: 91,
    matchReason: "時給1800円以上の高収入求人",
    highlights: [
      "皆勤手当 月3万円",
      "1R寮・Wi-Fi完備",
      "半年ごとに昇給あり",
    ],
    desc: "半導体製造装置のボタン操作・材料補充・データ入力を担当します。クリーンルーム内での作業のため、空調完備で快適です。",
    shiftDetails: ["早番 / 遅番 / 夜勤 の3交替制"],
    welfare: ["社会保険完備", "寮費無料", "送迎バスあり", "皆勤手当 3万円"],
  },
  {
    id: "J-20454",
    title: "コールセンタースタッフ",
    company: "メディコーポ久留米",
    companySize: "従業員 460名",
    location: "福岡県 久留米市",
    locationShort: "久留米市",
    access: "JR久大本線「久留米」駅徒歩5分",
    wage: 1450,
    wageType: "時給",
    wageNote: "月収例 27.8万円",
    category: "オフィス",
    subcategory: "コールセンター",
    shift: "日勤のみ",
    tags: ["在宅OK", "空調完備", "未経験OK", "長期歓迎"],
    photo: "assets/job-call.jpeg",
    color: "#2a2eea",
    color2: "#5e60ff",
    accent: "#dcf142",
    artLabel: "CALL CENTER",
    artIcon: "headset_mic",
    match: 79,
    matchReason: "空調完備・土日休みの希望に合致",
    highlights: ["完全週休2日制", "研修充実", "駅チカ"],
    desc: "お客様からのお問い合わせ対応業務です。マニュアル完備で未経験の方も安心。",
    shiftDetails: ["日勤: 9:00〜18:00 (実働8h)"],
    welfare: ["社保完備", "有給休暇", "制服貸与", "交通費全額"],
  },
  {
    id: "J-20455",
    title: "一般事務・データ入力",
    company: "ロジプラス関東",
    companySize: "従業員 280名",
    location: "千葉県 市川市",
    locationShort: "市川市",
    access: "JR総武線「市川」駅徒歩6分",
    wage: 1280,
    wageType: "時給",
    wageNote: "月収例 23.8万円",
    category: "オフィス",
    subcategory: "一般事務",
    shift: "日勤のみ",
    tags: ["日勤", "平日のみ", "シフト自由", "WワークOK"],
    photo: "assets/job-office.jpeg",
    color: "#2a2eea",
    color2: "#5e60ff",
    accent: "#dcf142",
    artLabel: "OFFICE · DATA ENTRY",
    artIcon: "desktop_windows",
    match: 72,
    matchReason: "平日シフトの希望条件にやや近い",
    highlights: ["1日4h〜OK", "履歴書不要", "即日勤務OK"],
    desc: "受発注データの入力・書類整理・電話応対など一般事務全般のお仕事です。",
    shiftDetails: ["日勤: 9:00〜18:00 (休憩1h)"],
    welfare: ["社保完備", "交通費支給", "Wワーク可"],
  },
  {
    id: "J-20456",
    title: "アパレル販売スタッフ",
    company: "西岡セレクト",
    companySize: "従業員 540名",
    location: "大阪府 東大阪市",
    locationShort: "東大阪市",
    access: "近鉄奈良線「八戸ノ里」駅徒歩2分",
    wage: 1580,
    wageType: "時給",
    wageNote: "月収例 30.5万円＋インセン",
    category: "販売",
    subcategory: "アパレル",
    shift: "シフト制",
    tags: ["社割あり", "正社員登用", "駅チカ"],
    photo: "assets/job-retail.jpeg",
    color: "#2a2eea",
    color2: "#5e60ff",
    accent: "#dcf142",
    artLabel: "RETAIL · APPAREL",
    artIcon: "storefront",
    match: 85,
    matchReason: "販売・接客の職歴にマッチ",
    highlights: ["社割30%OFF", "インセンティブ", "髪型自由"],
    desc: "カジュアルブランドのアパレル販売のお仕事。接客・品出し・フィッティング対応を行います。",
    shiftDetails: ["早番: 10:00〜19:00", "遅番: 12:00〜21:00"],
    welfare: ["社保完備", "社員割引", "交通費支給"],
  },
];

window.WM_HISTORY_LIKED = [
  { jobId: "J-20451", date: "4/21", reason: "給与" },
  { jobId: "J-20453", date: "4/20", reason: "寮・住居" },
  { jobId: "J-20456", date: "4/18", reason: "勤務地" },
];

window.WM_HISTORY_SKIPPED = [
  { jobId: "J-20455", date: "4/21", reason: "遠い" },
  { jobId: "J-20454", date: "4/20", reason: "シフト合わない" },
];
